### ISSUE TITLE
简历问题

### ISSUE THREAD

**Issue by gamedebug** [xiebohan789/test#1]
你公司网站多大？用户有多少？每天访问量多大？最大并发都少？监控哪些内容？监控数据如何处理？告警阈值如何设置？告警方式如何设置？被监控节点的agent工作模式是什么？为什么使用这种工作模式？shell脚本如何实现查看硬件损坏情况？

**Comment by xiebohan789** [comment]
好的，我会尽快完成修改，争取在周一20点前交任务
